name: A workflow for my Hello World file
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: environment
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Tag is: ${TAG}"
